FORMAT: 1A
HOST: http://cloud.api.gizwits.com

# Gizwits API for Private Cloud

# Group API for third-party clouds

## Devices [/devices?{product_key}&{limit,skip}]

### Register Devices [POST]

+ Request (application/json)

    + Header
        
            X-Gizwits-Application-Id: {appid}
            
    + Body
    
            {
                "devices": [{
                    "mac": "112233445566"
                }, {
                    "mac": "112233445566"
                }]
            }
            
+ Response 201 (application/json)

    + Body
    
            {
                "devices": [{
                    "did": "absew",
                    "mac": "112233445566"
                }, {
                    "did": "absew",
                    "mac": "112233445566"
                }]
            }

### Get Devices [GET]

Devices are ordered by created_at descending.

+ Parameters
    + product_key (optional, string, `abcde`) ... If not provided, will return this cloud's own devices.
    + limit (optional, number, `20`)
    + skip (optional, number, `0`)

+ Request (application/json)

    + Header
        
            X-Gizwits-Application-Id: {appid}
            
+ Response 200 (application/json)

    + Body
    
            {
                "devices": [{
                    "pdid": "absew",
                    "mac": "112233445566",
                    "puids": ["adfadf", "adafd"]
                }, {
                    "pdid": "absew",
                    "mac": "112233445566",
                    "puids": ["adfadf", "adafd"]
                }]
            }
            
## Bindings [/bindings]

### Register Bindings [POST]

+ Request (application/json)

    + Header
        
            X-Gizwits-Application-Id: {appid}
            
    + Body
    
            {
                "bindings": [{
                    "user": "112233445566",
                    "devices": ["abcde", "adfade"]
                }, {
                    "user": "112233445566",
                    "devices": ["abcde", "adfade"]
                }]
            }
            
+ Response 201 (application/json)

### Delete Bindings [DELETE]

+ Request (application/json)

    + Header
        
            X-Gizwits-Application-Id: {appid}
            
    + Body
    
            {
                "bindings": [{
                    "user": "112233445566",
                    "devices": ["abcde", "adfade"]
                }, {
                    "user": "112233445566",
                    "devices": ["abcde", "adfade"]
                }]
            }
            
+ Response 200 (application/json)

## Device History Data [/devdata/{did}]

+ Parameters
    + did (required, string, `abadc`)

### Save History Data [POST]

+ Request (application/json)

    + Header
        
            X-Gizwits-Application-Id: {appid}
            
    + Body
    
            {
                "data": [{
                    "ts": 123239009,
                    "payload": "aieowkefmm"
                }, {
                    "ts": 123239009,
                    "payload": "aieowkefmm"
                }]
            }
            
+ Response 201 (application/json)

### Get history Data [GET]

+ Request (application/json)

    + Header
        
            X-Gizwits-Application-Id: {appid}

+ Response 201 (application/json)

    + Body
    
            {
                "data": [{
                    "ts": 123239009,
                    "payload": "aieowkefmm"
                }, {
                    "ts": 123239009,
                    "payload": "aieowkefmm"
                }]
            }
            
## Remote Control Device [/devices/{did}]

+ Parameters
    + did (required, string, `abadc`)
    
### Set Data to Device [POST]

+ Request (application/json)

    + Header
        
            X-Gizwits-Application-Id: {appid}
            
    + Body
        
            {
                "data": [{
                    "attr": "abc",
                    "val": 1
                }]
            }

+ Response 200 (application/json)
